workflows:
  ios_build:
    name: ios build workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
      vars:
        flutter: stable
        xcode: latest
        cocoapods: 1.9.1
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/Cocaopods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: ramdan_dev2
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script:  flutter packages pub get
      - name : Build IOS
        script: flutter build ios