/// Flutter icons DiscipleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiscipleIcons
///      fonts:
///       - asset: fonts/DiscipleIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DiscipleIcons {
  DiscipleIcons._();

  static const _kFontFam = 'DiscipleIcons';
  static const String? _kFontPkg = null;

  static const IconData linkedin = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_red_small_size = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_red = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_white = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
