/// Flutter icons HabitozIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HabitozIcons
///      fonts:
///       - asset: fonts/HabitozIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HabitozIcons {
  HabitozIcons._();

  static const _kFontFam = 'HabitozIcons';
  static const String? _kFontPkg = null;

  static const IconData airConditioner = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antDesignCameraFilled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cctv = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarityShareLine = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codiconMenu = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downArrow = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elevator = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData epSearch = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fb = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileEarMarkText = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluentBookContacts20Regular = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluentEdit16Regular = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_2195 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locker = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData others = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phMapPinThin = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pool = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioButton2 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioButton = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_2120 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shutdown = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideUp1 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideUp = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconsTickCircleSolid = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vectorStroke = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
